sudo pacman -S --noconfirm acpi
sudo pacman -S --noconfirm acpitool
sudo pacman -S --noconfirm adapta-gtk-theme
sudo pacman -S --noconfirm adobe-source-code-pro-fonts
sudo pacman -S --noconfirm adobe-source-han-mono-cn-fonts
sudo pacman -S --noconfirm adobe-source-han-mono-tw-fonts
sudo pacman -S --noconfirm adobe-source-han-sans-cn-fonts
sudo pacman -S --noconfirm adobe-source-han-sans-tw-fonts
sudo pacman -S --noconfirm adobe-source-serif-pro-fonts
sudo pacman -S --noconfirm alacritty
sudo pacman -S --noconfirm alsa-utils
sudo pacman -S --noconfirm arc-icon-theme
sudo pacman -S --noconfirm autoconf
sudo pacman -S --noconfirm automake
sudo pacman -S --noconfirm base
sudo pacman -S --noconfirm bash-language-server
sudo pacman -S --noconfirm bc
sudo pacman -S --noconfirm binutils
sudo pacman -S --noconfirm bison
sudo pacman -S --noconfirm chromium
sudo pacman -S --noconfirm ctags
sudo pacman -S --noconfirm dbus-glib
sudo pacman -S --noconfirm dhcp
sudo pacman -S --noconfirm dhcpcd
sudo pacman -S --noconfirm dunst
sudo pacman -S --noconfirm efibootmgr
sudo pacman -S --noconfirm ethtool
sudo pacman -S --noconfirm fakeroot
sudo pacman -S --noconfirm fcitx
sudo pacman -S --noconfirm fcitx-configtool
sudo pacman -S --noconfirm fcitx-gtk2
sudo pacman -S --noconfirm fcitx-gtk3
sudo pacman -S --noconfirm fcitx-libpinyin
sudo pacman -S --noconfirm fcitx-qt5
sudo pacman -S --noconfirm feh
sudo pacman -S --noconfirm flex
sudo pacman -S --noconfirm fuse2
sudo pacman -S --noconfirm fzf
sudo pacman -S --noconfirm gcc
sudo pacman -S --noconfirm git
sudo pacman -S --noconfirm gnome-screenshot
sudo pacman -S --noconfirm google-chrome
sudo pacman -S --noconfirm groff
sudo pacman -S --noconfirm grub
sudo pacman -S --noconfirm htop
sudo pacman -S --noconfirm intel-media-driver
sudo pacman -S --noconfirm kdenlive
sudo pacman -S --noconfirm kjv-apocrypha
sudo pacman -S --noconfirm lazygit
sudo pacman -S --noconfirm libreoffice-fresh
sudo pacman -S --noconfirm libtool
sudo pacman -S --noconfirm linux
sudo pacman -S --noconfirm linux-firmware
sudo pacman -S --noconfirm llpp
sudo pacman -S --noconfirm lxappearance
sudo pacman -S --noconfirm m4
sudo pacman -S --noconfirm make
sudo pacman -S --noconfirm mono
sudo pacman -S --noconfirm mutt-wizard-git
sudo pacman -S --noconfirm neofetch
sudo pacman -S --noconfirm neomutt
sudo pacman -S --noconfirm neovim
sudo pacman -S --noconfirm nerd-fonts-source-code-pro
sudo pacman -S --noconfirm network-manager-applet
sudo pacman -S --noconfirm npm
sudo pacman -S --noconfirm os-prober
sudo pacman -S --noconfirm pam-gnupg-git
sudo pacman -S --noconfirm patch
sudo pacman -S --noconfirm picom-git
sudo pacman -S --noconfirm pkgconf
sudo pacman -S --noconfirm python
sudo pacman -S --noconfirm python-pip
sudo pacman -S --noconfirm python2
sudo pacman -S --noconfirm python2-pip
sudo pacman -S --noconfirm ranger-git
sudo pacman -S --noconfirm screenkey
sudo pacman -S --noconfirm simplescreenrecorder
sudo pacman -S --noconfirm smartmontools
sudo pacman -S --noconfirm sudo
sudo pacman -S --noconfirm terminus-font
sudo pacman -S --noconfirm texinfo
sudo pacman -S --noconfirm thunar
sudo pacman -S --noconfirm tlp
sudo pacman -S --noconfirm trayer
sudo pacman -S --noconfirm ttf-font-awesome
sudo pacman -S --noconfirm ttf-i.bming
sudo pacman -S --noconfirm ttf-inconsolata
sudo pacman -S --noconfirm ttf-joypixels
sudo pacman -S --noconfirm ttf-linux-libertine
sudo pacman -S --noconfirm ttf-symbola
sudo pacman -S --noconfirm ttf-twemoji-color
sudo pacman -S --noconfirm unzip
sudo pacman -S --noconfirm vlc
sudo pacman -S --noconfirm w3m
sudo pacman -S --noconfirm wget
sudo pacman -S --noconfirm which
sudo pacman -S --noconfirm wireless_tools
sudo pacman -S --noconfirm wpa_supplicant
sudo pacman -S --noconfirm wqy-bitmapfont
sudo pacman -S --noconfirm wqy-microhei
sudo pacman -S --noconfirm wqy-microhei-lite
sudo pacman -S --noconfirm wqy-zenhei
sudo pacman -S --noconfirm xclip
sudo pacman -S --noconfirm xdialog
sudo pacman -S --noconfirm xf86-video-intel
sudo pacman -S --noconfirm xfce4-power-manager
sudo pacman -S --noconfirm xfce4-volumed-pulse
sudo pacman -S --noconfirm xorg-docs
sudo pacman -S --noconfirm xorg-fonts-100dpi
sudo pacman -S --noconfirm xorg-fonts-75dpi
sudo pacman -S --noconfirm xorg-iceauth
sudo pacman -S --noconfirm xorg-luit
sudo pacman -S --noconfirm xorg-server
sudo pacman -S --noconfirm xorg-server-common
sudo pacman -S --noconfirm xorg-server-devel
sudo pacman -S --noconfirm xorg-server-xdmx
sudo pacman -S --noconfirm xorg-server-xephyr
sudo pacman -S --noconfirm xorg-server-xnest
sudo pacman -S --noconfirm xorg-server-xvfb
sudo pacman -S --noconfirm xorg-server-xwayland
sudo pacman -S --noconfirm xorg-sessreg
sudo pacman -S --noconfirm xorg-setxkbmap
sudo pacman -S --noconfirm xorg-smproxy
sudo pacman -S --noconfirm xorg-x11perf
sudo pacman -S --noconfirm xorg-xauth
sudo pacman -S --noconfirm xorg-xbacklight
sudo pacman -S --noconfirm xorg-xcmsdb
sudo pacman -S --noconfirm xorg-xcursorgen
sudo pacman -S --noconfirm xorg-xdpyinfo
sudo pacman -S --noconfirm xorg-xdriinfo
sudo pacman -S --noconfirm xorg-xev
sudo pacman -S --noconfirm xorg-xgamma
sudo pacman -S --noconfirm xorg-xhost
sudo pacman -S --noconfirm xorg-xinit
sudo pacman -S --noconfirm xorg-xinput
sudo pacman -S --noconfirm xorg-xkbcomp
sudo pacman -S --noconfirm xorg-xkbevd
sudo pacman -S --noconfirm xorg-xkbutils
sudo pacman -S --noconfirm xorg-xkill
sudo pacman -S --noconfirm xorg-xlsatoms
sudo pacman -S --noconfirm xorg-xlsclients
sudo pacman -S --noconfirm xorg-xmodmap
sudo pacman -S --noconfirm xorg-xpr
sudo pacman -S --noconfirm xorg-xprop
sudo pacman -S --noconfirm xorg-xrandr
sudo pacman -S --noconfirm xorg-xrdb
sudo pacman -S --noconfirm xorg-xrefresh
sudo pacman -S --noconfirm xorg-xset
sudo pacman -S --noconfirm xorg-xsetroot
sudo pacman -S --noconfirm xorg-xvinfo
sudo pacman -S --noconfirm xorg-xwd
sudo pacman -S --noconfirm xorg-xwininfo
sudo pacman -S --noconfirm xorg-xwud
sudo pacman -S --noconfirm yay
sudo pacman -S --noconfirm zip
sudo pacman -S --noconfirm zsh
sudo pacman -S --noconfirm fish neovim xorg-xinit xorg-server nodejs fzf the_silver_searcher npm
sudo pacman -S --noconfirm dmenu alacritty picom ranger picom
# 安装awesom
sudo pacman -S --noconfirm cmake lua converseen libxdg-basedir xcb-util-xrm lua-lgi 
sudo pacman -S --noconfirm amixer dmenu mpc mpd scrot unclutter xorg-xbacklight xsel slock urxvt-perls 
sudo pacman -S --noconfirm oft-font-awesome dex libchamplain rofi picom ncmpcpp xfce4-power-manager flameshot btop nitrogen
# 安装polybar
sudo pacman -S --noconfirm zoxide polybar i3
sudo pacman -S --noconfirm bluez bluez-utils
# sudo systemctl enable bluetooth.service
# sudo systemctl start bluetooth.service
# 配置nvim lua
sudo pacman -Sy --noconfirm firefox go lua-language-server shellcheck shfmt stylua figlet ctags fd rubygems php julia
sudo pacman -Sy --noconfirm cargo luarocks ruby